spring:
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    validate-migration-naming: true

jwt:
  key: ${JWT_KEY}
  expiration: ${EXPIRATION_TOKEN}
resilience4j:
  ratelimiter:
    instances:
      authRegister:
        timeout-duration: 0
        limit-for-period: 5
        limit-refresh-period: 60s
      authLogin:
        timeout-duration: 0
        limit-for-period: 5
        limit-refresh-period: 60s
adm:
  username: ${ADMIN}
  password: ${PASSWORD}